### PR TITLE
Added link to Minio Puppet module

### PR DESCRIPTION
**Pull request by danielsreichenbach**
This adds a new entry to the DevOps section mentioning the availability of a Puppet module to manage Minio installations.

### CODE REVIEW

**Comment by nitisht** [comment]
Thank you for the contribution @danielsreichenbach 

We also have a cookbook repo https://github.com/minio/cookbook as well, would you like to contribute detailed steps to get started with Minio-Puppet module there?

**Comment by harshavardhana** [comment]
Can rebase your changes @danielsreichenbach with master.. to the CI to rebuild.

**Comment by danielsreichenbach** [comment]
Done.

**Comment by harshavardhana** [comment]
> Done.

Thanks

**Review by harshavardhana — APPROVED** [review]

**Review by nitisht — APPROVED** [review]

**Pull request merged**
