### PR TITLE
Update Deis > Team Hephy

### PR DESCRIPTION
**Pull request by till**
Hephy Workflow is the continuation of Deis Workflow. Actively developed and maintained.

### CODE REVIEW

**Review by nitisht — APPROVED** [review]

**Comment by kannappanr** [comment]
`s3-resource-simple` links have to be fixed. The links are `https://concourse-ci.org/` and `https://github.com/18F/s3-resource-simple` to fix the Travis failures

**Comment by till** [comment]
@nitisht @kannappanr Fix the links here or in another PR? Let me know.

**Comment by nitisht** [comment]
>  Fix the links here or in another PR? Let me know.

I see the wrong link is not a part of this PR, still if you don't mind please update it in this PR itself.

**Comment by till** [comment]
@nitisht No problem, ✅

**Comment by kannappanr** [comment]
@till Thanks for the PR

**Review by kannappanr — APPROVED** [review]

**Pull request merged**
