### PR TITLE
add Minio app on Univention to the listing

### PR DESCRIPTION
**Pull request by fbartels**
The Minio app for Univention has been published today and can now be downloaded from the Univention app center.

### CODE REVIEW

**Comment by fbartels** [comment]
The build failure is not related and is a 404 on an already existing link (https://www.hyperscalers.com/quanta-qct-server-1u-quantagrid-d51b-2u-buy-quantagridd51b2u-distribution-buy-usa-aus)

**Comment by kannappanr** [comment]
The link probably should be changed to `http://www.hyperscalers.com.au/quanta-qct-server-1u-quantagrid-d51b-2u-buy-quantagridd51b2u-distribution-buy-usa-aus`

**Comment by harshavardhana** [comment]
> The link probably should be changed to http://www.hyperscalers.com.au/quanta-qct-server-1u-quantagrid-d51b-2u-buy-quantagridd51b2u-distribution-buy-usa-aus

Can you do that @fbartels ? h

**Comment by harshavardhana** [comment]
The link is fixed @kannappanr @fbartels https://github.com/minio/awesome-minio/pull/73

**Review by harshavardhana — APPROVED** [review]

**Review by nitisht — APPROVED** [review]

**Pull request merged**
